// Extracts ABIs from the Foundry build output into a typed TS module.
// Run after `forge build`:  pnpm --filter @swing/shared gen-abis
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "../../..");
const outDir = resolve(root, "contracts/out");
const dest = resolve(here, "../src/abis/index.ts");

const contracts = {
  reputationOracleAbi: "ReputationOracle",
  creditVaultAbi: "CreditVault",
  creditManagerAbi: "CreditManager",
  guardedAccountAbi: "GuardedAccount",
  guardedAccountFactoryAbi: "GuardedAccountFactory",
  spendingGuardHookAbi: "SpendingGuardHook",
  spendingGuardValidatorAbi: "SpendingGuardValidator",
  mockUsdcAbi: "MockUSDC",
};

let out =
  "// AUTO-GENERATED by scripts/gen-abis.mjs — do not edit by hand.\n" +
  "// Regenerate after changing contracts: pnpm --filter @swing/shared gen-abis\n\n";

let count = 0;
for (const [name, contract] of Object.entries(contracts)) {
  const path = resolve(outDir, `${contract}.sol/${contract}.json`);
  try {
    const abi = JSON.parse(readFileSync(path, "utf8")).abi;
    out += `export const ${name} = ${JSON.stringify(abi)} as const;\n\n`;
    count++;
  } catch (e) {
    console.warn(`skip ${contract}: ${e.message}`);
  }
}

mkdirSync(dirname(dest), { recursive: true });
writeFileSync(dest, out);
console.log(`wrote ${count} ABIs -> ${dest}`);
